### ISSUE TITLE
マウスホイールで操作時エラーが出る

### ISSUE THREAD

**Issue by kkri3** [shinyaishida/mjai#17]
エラーが出るバージョン 613c6ad

手順
1.  mjson.htmlをchromeで開く
2. .mjsonファイルを読み込む
3. マウスホイールを上下に操作する（prev,nextを移動）
4. コンソールに下記のエラーが出る

エラー出力
`jquery-1.7.2.min.js:3 [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/6662647093133312`

**Comment by shinyaishida** [comment]
マウスホイールを使わなくした。
