### ISSUE TITLE
卓の HTML をサーバーから配信する

### ISSUE THREAD

**Issue by shinyaishida** [shinyaishida/mjai#33]
リポジトリをローカルにクローンしなくてもプレイできるようにする

**Comment by shinyaishida** [comment]
サーバーが Ruby で実装されているので Rails でやってみる

**Comment by shinyaishida** [comment]
必要な概念
- ユーザー (もしくはプレイヤー): 一意の名前をもつ
- 部屋: ユーザーが 4 名集まる

**Comment by shinyaishida** [comment]
- ユーザーは mjai メッセージを送受信するために WebSocket でサーバーと繋がる。
- それぞれの WebSocket は独立している。

**Comment by shinyaishida** [comment]
- トップページから部屋に遷移する際にユーザーのセッションを維持しないといけない。

**Comment by shinya-asterisk** [comment]
こんなイメージ。赤破線内がこの issue で取り組む範囲。
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/91529415/135700484-9a2592a8-e832-4234-aa41-2b784a488ece.png">
