### ISSUE TITLE
Ruby 2.7 で実行できるようにする

### ISSUE THREAD

**Issue by shinyaishida** [shinyaishida/mjai#4]
1.9.1 -> 2.7.x

**Comment by shinyaishida** [comment]
諸事情によりとりあえず 2.6

**Comment by shinyaishida** [comment]
```
gem build mjai.gemspec
```
は成功。

**Comment by kkri3** [comment]
% gem build mjai.gemspec

```
NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed on or after 2018-12-01.
Gem::Specification#has_rdoc= called from mjai.gemspec:16.
WARNING:  license value 'New BSD' is invalid.  Use a license identifier from
http://spdx.org/licenses or 'Nonstandard' for a nonstandard license.
Did you mean '0BSD'?
WARNING:  description and summary are identical
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: mjai
  Version: 0.0.7
  File: mjai-0.0.7.gem
```

**Comment by shinyaishida** [comment]
WARNING のところは後で直す。

**Comment by shinyaishida** [comment]
とりあえず mjai が動くか試す。

**Comment by kkri3** [comment]
ippei@ippeinoMacBook-Air mjai % ./bin/mjai server --port==11600 --game_type=one_kyoku --room=default --log_dir=/mjai/log mjai-shanten mjai-shanten mjai-shanten 
NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed on or after 2018-12-01.
Gem::Specification#has_rdoc= called from /Users/ippei/dev/mjai/mjai.gemspec:16.
Bundler could not find compatible versions for gem "sass":
  In Gemfile:
    mjai was resolved to 0.0.7, which depends on
      sass (= 3.1.0)

Could not find gem 'sass (= 3.1.0)', which is required by gem 'mjai', in any of the sources.
ippei@ippeinoMacBook-Air mjai % bundle 
NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed on or after 2018-12-01.
Gem::Specification#has_rdoc= called from /Users/ippei/dev/mjai/mjai.gemspec:16.
Fetching gem metadata from http://rubygems.org/.............
Fetching gem metadata from http://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    mjai was resolved to 0.0.7, which depends on
      bundler (= 1.0.0)

  Current Bundler version:
    bundler (1.17.2)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (= 1.0.0)', which is required by gem 'mjai', in any of the sources.

**Comment by shinyaishida** [comment]
mjai.gemspec の bundler のバージョンを 1.17.2 にしてみる

**Comment by shinyaishida** [comment]
またまた諸事情で 2.7.2 でやることに。

**Comment by kkri3** [comment]
mjai.gemspecのjson行削除
Gemfileにgem "json"追記

**Comment by shinyaishida** [comment]
bundle install 成功

**Comment by kkri3** [comment]
実行コマンド
```
./bin/mjai server --port=11600 --game_type=one_kyoku --room=default --log_dir=log mjai-shanten mjai-shanten mjai-shanten
```

**Comment by kkri3** [comment]
クライアント側実行コマンド
```
./bin/mjai-shanten mjsonp://127.0.0.1:11600/default
```

**Comment by kkri3** [comment]
動いた！
