### ISSUE TITLE
Chromeで牌がちかちかする不具合

### ISSUE THREAD

**Issue by nakamuloud** [shinyaishida/mjai#41]
Win/Mac両方で発生。
1手ごとに4回くらい更新されている。
例えば手配の更新のされかたが、牌の数が1から13までどんどん足されて行っているような描画になっている
=>手牌の更新時に、手牌配列が空になって、Pushされていっている疑惑

**Comment by shinyaishida** [comment]
Chrome で発生。Firefox ではちらつかない。

**Comment by shinyaishida** [comment]
レンダリング処理を見直してちらつきを消した。
- 手牌、副露、河をレンダリングするときに牌列を空にしないようにした。
- 牌列が伸びる方向に `img` 要素を挿入するようにした。
