### ISSUE TITLE
コンテナ外からクライアント接続できるようにする

### ISSUE THREAD

**Issue by shinyaishida** [shinyaishida/mjai#6]
docker-compose.yml では 11600:11600 でポートをバインドしているけど、コンテナ外からだと、なぜかクライアントがうまく繋がらない。

**Comment by kkri3** [comment]
Docker ではinet 172.18.0.2/16で動いてる
local(MAC)->docker  ./mjai-shnten~~
```
1	0.000000	172.18.0.1	172.18.0.2	TCP	74	62662 → 11600 [SYN] Seq=0 Win=64240 Len=0 MSS=1460 SACK_PERM=1 TSval=2717895625 TSecr=0 WS=128
2	0.000020	172.18.0.2	172.18.0.1	TCP	54	11600 → 62662 [RST, ACK] Seq=1 Ack=1 Win=0 Len=0
```
local(MAC)->docker  nc 127.0.0.1 16100
succeeded

**Comment by shinyaishida** [comment]
https://stackoverflow.com/questions/57773604/connection-reset-by-peer-when-when-hitting-docker-container

**Comment by kkri3** [comment]
--host=0.0.0.0で動きそう

**Comment by shinyaishida** [comment]
docker-compose up すると
```
... block in materialize': Could not find ...
```
というエラーが出るのは Dockerfile の中で bundle install してないから。

**Comment by shinyaishida** [comment]
Dockerfile の最後に RUN bundle install を追記すればいい。

**Comment by shinyaishida** [comment]
370dc4115f3eb7ac56a2cc55742ed4f5d14065d7
